[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Community Practices"
authors = [{name = "Sarah Goodale", email = "sarah.e.goodale@vanderbilt.edu"}]
dynamic = ["version", "description"]
